// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq1gsvgVqdbsR6HXJbXXiYVHCTuFYyWgw',
    appId: '1:1098215056967:web:ce8d5c7e3352ca4c44f362',
    messagingSenderId: '1098215056967',
    projectId: 'upstyleapp-c0154',
    authDomain: 'upstyleapp-c0154.firebaseapp.com',
    storageBucket: 'upstyleapp-c0154.appspot.com',
    measurementId: 'G-YS1NYTSDZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB-pshj-09Su1u04P0D7K3JjSIv7kL0rY',
    appId: '1:1098215056967:android:22403c28c9e5a5d744f362',
    messagingSenderId: '1098215056967',
    projectId: 'upstyleapp-c0154',
    storageBucket: 'upstyleapp-c0154.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh4rBA0RwcnVhqzCSRZsDHihcKQ000-RA',
    appId: '1:1098215056967:ios:5224f4ef5c5b6d0d44f362',
    messagingSenderId: '1098215056967',
    projectId: 'upstyleapp-c0154',
    storageBucket: 'upstyleapp-c0154.appspot.com',
    iosBundleId: 'com.example.upstyle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh4rBA0RwcnVhqzCSRZsDHihcKQ000-RA',
    appId: '1:1098215056967:ios:d65b51b60a7ca33e44f362',
    messagingSenderId: '1098215056967',
    projectId: 'upstyleapp-c0154',
    storageBucket: 'upstyleapp-c0154.appspot.com',
    iosBundleId: 'com.example.upstyle.RunnerTests',
  );
}
